# docker-compose.yml
version: '3.8'

services:
  db_mysql:
    image: mysql:8.0
    container_name: mysql_pecas_api
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_api_data:/var/lib/mysql

volumes:
  mysql_api_data:
